<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modèle" nsURI="http://m2sdl.modèle" nsPrefix="modèle">
  <eClassifiers xsi:type="ecore:EEnum" name="Fonction">
    <eLiterals name="Analyst"/>
    <eLiterals name="Designer" value="1"/>
    <eLiterals name="Programmeur" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Projet" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membres" lowerBound="2"
        upperBound="-1" eType="#//Membre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chef" lowerBound="1" eType="#//Membre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" lowerBound="2" upperBound="-1"
        eType="#//Role" changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Membre" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projets" upperBound="-1"
        eType="#//Projet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projetsGeres" upperBound="-1"
        eType="#//Projet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fonction" eType="#//Fonction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="membre" eType="#//Membre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projet" eType="#//Projet"/>
  </eClassifiers>
</ecore:EPackage>
